site_name: Workshop Web-Design for Scientists
copyright: > # should remain a link to the original theme
  &copy; 2023 Julia-Katharina Pfarr<br>

repo_name: julia-pfarr/workshop_webdesign
repo_url: https://github.com/julia-pfarr/workshop_webdesign

theme:
  name: material
  custom_dir: material
  palette:
    primary: blue grey
    accent: custom
  #if custom color, instead (paired with extra_css below):
    #primary: custom
    #accent: custom  
  font: 
    text: Montserrat
    code: Roboto Mono  
  language: en
  logo: assets/images/nowa-white.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
    - toc.integrate

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jk_pfarr

#extra_css:
  #- stylesheets/extra.css 

docs_dir: docs

nav:
- Home: index.md
- Installing: installing.md
- Customization: custom.md
- Creating a Landing Page: landing.md
- Pretty and useful extras: extras.md
- Deployment on GitHub: deploy.md
- Further resources: resources.md


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.pathconverter:
      base_path: 'julia-pfarr/workshop_webdesign' 
      relative_path: '../../artifacts/example.pdf'
      absolute: false # default: false
      tags: ''    
